config/routes.rb
Rails.application.routes.draw do
  
  root to:"items#index"
  devise_for :users
  get 'items/index'
  get 'items/search'
  resources :items,only:[:index,:new,:create,:show,:edit,:update,:destroy] do 
    resources :orders,only:[:index,:create]
    resources :comments,only: :create
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/adress.rb
class Adress < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
    {id: 0, name: '--'}, {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, 
    {id: 3, name: '岩手県'}, {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, 
    {id: 6, name: '山形県'}, {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, 
    {id: 9, name: '栃木県'}, {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, 
    {id: 12, name: '千葉県'}, {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, 
    {id: 15, name: '新潟県'}, {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, 
    {id: 18, name: '福井県'}, {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, 
    {id: 21, name: '岐阜県'}, {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, 
    {id: 24, name: '三重県'}, {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, 
    {id: 27, name: '大阪府'}, {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, 
    {id: 30, name: '和歌山県'}, {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, 
    {id: 33, name: '岡山県'}, {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, 
    {id: 36, name: '徳島県'}, {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, 
    {id: 39, name: '高知県'}, {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, 
    {id: 42, name: '長崎県'}, {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, 
    {id: 45, name: '宮崎県'}, {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    {id: 0, name:"--"},
    {id: 1, name:"レディース"},
    {id:2,  name:"メンズ"},
    {id:3,  name:"ベビー・キッズ"},
    {id:4,  name:"インテリア・小物"},
    {id:5,  name:"本・音楽・ゲーム"},
    {id:6,  name:"おもちゃ"}
  ]
  
  include ActiveHash::Associations
  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
  
end

app/models/days.rb
class Days < ActiveHash::Base
  self.data = [
    {id:0,name:"--"},
    {id:1,name:"１０日以内"},
    {id:2,name:"5日以内"}
  ]
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_one_attached :image
  has_one :order
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :yamato
  belongs_to :category
  has_one :pay
  validates :image ,presence: true
  
  with_options presence: true,numericality:{other_than:0} do
  validates :area_id,:item_category_id,:yamato_id,:days_id,:item_statue_id
  end
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_adress.rb
class OrderAdress
  include ActiveModel::Model
  attr_accessor :sikutyouson,:banti,:yubin,:building,:area,:phone,:item_id,:item,:cost,:token,:user_id
  def save
    @order = Order.create(cost:cost,item_id:item_id,user_id:user_id)
    @adress = Adress.create(sikutyouson:sikutyouson,banti:banti,yubin:yubin,building:building,area:area,phone:phone,order_id:@order.id)
  end
  validates :yubin,format:{with:/\A[0-9]{3}-[0-9]{4}\z/}

end

app/models/statue.rb
class Statue < ActiveHash::Base
  self.data = [
    {id:1,name:"--"},
    {id:2,name:"良好"},
    {id:3,name:"普通"},
    {id:4,name:"悪い"}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items
  has_many :comments
  has_many :orders

  with_options presence: true do
    validates :nickname
    validates :first_name, format:{with:/\A[ぁ-んァ-ン一-龥]/,message:"is invalid. Input full-width characters."}
    validates :last_name, format:{with:/\A[ぁ-んァ-ン一-龥]/,message:"is invalid. Input full-width characters."}
  end
end

app/models/yamato.rb
class Yamato < ActiveHash::Base
  self.data = [
    
    {id:2,name:"手数料払う"},
    {id:3,name:"払わない"}
  ]
  include ActiveHash::Associations
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_paramater, if: :devise_controller?
  private
  def configure_permitted_paramater
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :email, :birth_date, :first_name, :last_name, :first_name_kana, :last_name_kana])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action:authenticate_user!
  def create
    @comment = Comment.new(comment_params)
    
    if @comment.valid?
      @comment.save
      redirect_to item_path(params[:item_id])
    else
      render :create
    end
  end
  private
  def comment_params
    params.require(:comment).permit(:content).merge(item_id:params[:item_id],user_id:current_user.id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  before_action :already_order,except:[:index,:show,:new,:create,:search]
  before_action :search_item,only: [:index,:search]
  def index
    @items = Item.all
    category_item
  end
  def new
    @item = Item.new
  end
  def create
    @item = Item.new(item_params)
    if @item.valid?
      @item.save
      redirect_to root_path
    else
      render :new
    end
  end
  def show
    @item = Item.find(params[:id])
    @comment = Comment.new
    @comments = @item.comments.all
  end
  def edit
    @item = Item.find(params[:id])
  end
  def update
    item = Item.find(params[:id])
    if item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end
  def destroy
    item = Item.find(params[:id])
    if item.destroy
      redirect_to root_path
    else
      render :show
    end
  end
  def search
    @results = @p.result
  end
  private
  def item_params
    params.require(:item).permit(:item_name,:item_category_id,:item_statue_id,:yamato_id,:cost,:area_id,:days_id,:image,:item_text).merge(user_id: current_user.id)
  end
  def already_order
    @item = Item.find(params[:id])
    if  @item.order != nil
      redirect_to root_path
    end
  end
  def search_item
    @p = Item.ransack(params[:q])
  end
  def category_item
    @category = Category.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :move_to_index
  before_action :item_user
  def index
    @item = Item.where(id:params[:item_id])
    @orderadress = OrderAdress.new
  end
  def create
    @item = Item.find(params[:item_id])
    @orderadress = OrderAdress.new(order_adress_params)
    if @orderadress.valid?
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"] 
      Payjp::Charge.create(
        amount: order_adress_params[:cost],
        card: order_adress_params[:token],
        currency: 'jpy'
      )
      @orderadress.save
      return redirect_to root_path
    else
      render item_path(@item.id)
    end
  end
  private
  def order_adress_params
    params.permit(:phone,:banti,:sikutyouson,:building,:yubin,:area).merge(token:params[:token],item_id:@item.id,cost:@item.cost,user_id:current_user.id)
  end
  def move_to_index
    @item = Item.find(params[:item_id])
    if  @item.order != nil
      redirect_to root_path
    end
  end
  def item_user
    if @item.user_id == current_user.id
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boughts_helper.rb
module BoughtsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/items/_result_item.html.erb
<%= results.item_name%>

app/views/items/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>

<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model:@item ,local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%# render 'shared/error_messages', model: f.object %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :item_name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :item_text, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:item_category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:item_statue_id, Statue.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:yamato_id, Yamato.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:days_id, Days.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
    <%# /配送について %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :hoge, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', "#", class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      人生を変えるフリマアプリ
    </h2>
    <p class='service-explain'>
      FURIMAはだれでもかんたんに出品・購入できる
    </p>
    <p class='service-explain'>
      フリマアプリです
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面上部の「人生を変えるフリマアプリ」帯部分  %>

  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      FURIMAが選ばれる3つの理由
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "furima-intro01.png", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>3分</span>
          ですぐに出品
        </h3>
        <p class='reason-list-description'>
          スマホで入力するだけで簡単に出品できる！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro02.png", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>シンプル</span>
          で使いやすい
        </h3>
        <p class='reason-list-description'>
          めんどくさい入力は必要なく、検索も購入もスムーズ！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro03.png", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          手数料
          <span class='reason-list-blue-text'>業界最安</span>
        </h3>
        <p class='reason-list-description'>
          10%でお得に出品&購入！
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAが選ばれる3つの理由部分 %>

  <%# 画面中央の「会員数日本一位」帯部分 %>
  <div class='ad-contents'>
    <h2 class='ad-title'>
      会員数日本一位
    </h2>
    <p class='ad-explain'>
      FURIMAは、フリマアプリで最も人気。
    </p>
    <p class='ad-explain'>
      出品・購入回数も業界最多です！
    </p>
    <p class='ad-explain'>
      ほしかったあの商品に出会えるかもしれません。
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面中央の「会員数日本一位」帯部分 %>

  <%# FURIMAの特徴 %>
  <div class='feature-contents'>
    <h2 class='title'>
      FURIMAの特徴
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "furima-intro04.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          簡単に売り買いできる
        </h3>
        <p class='feature-list-description'>
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro05.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          売上金は即日振込みに対応
        </h3>
        <p class='feature-list-description'>
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro06.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          様々な支払いに対応
        </h3>
        <p class='feature-list-description'>
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAの特徴 %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <%if @item != nil%>
    <%= link_to '新規投稿商品',  item_orders_path(@item.id), class: "subtitle" %>
    <%end%>
    <%= link_to "投稿", new_item_path%>
    <ul class='item-lists'>

      <% @items.each do |item|%>
      <li class='list'>
      <%= link_to "詳細", item_path(item.id)%>
        <div class='item-img-content'>
          <%= link_to item_path(item.id) do%>
          <%= image_tag item.image ,class: "item-img" %>
          <%if item.order != nil%>
          <div class='sold-out'>
            <span>Sold Out!!</span>
          </div>
          <%end%>
          

        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.item_name %>
          </h3>
          <div class='item-price'>
            <span><%= item.cost %>円<br><%= item.yamato.name %></span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        
      <%end%>
      </li>
      <%end%>

      <%#if @items.null %>
      <%# 商品がある場合は表示されないようにしましょう %>
      <li class='list'>
        <%= link_to root_path do %>
        <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "item-img" %>
        <div class='item-info'>
          <h3 class='item-name'>
            商品を出品してね！
          </h3>
          <div class='item-price'>
            <span>99999999円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <%#end%>
      <%#end%>
    </ul>
  </div>
  <%# /商品一覧 %>
</div>
<%= link_to(new_item_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>出品する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/items/search.html.erb
<%@results.each do |r|%>
<%= image_tag r.image%>
<%=r.item_name%>

<%end%>

app/views/items/show.html.erb
<%= render "shared/header" %>


<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.item_name%>
    </h2>
    <div class="item-img-content">
      <%= image_tag @item.image ,class:"item-box-img" %>
      <%if @item.order != nil %>
      <div class="sold-out">
        <span>Sold Out!!</span>
      </div>
      <%else%>
      <div class="sold-out">
      </div>
      <%end %>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        <%=@item.cost%>円
      </span>
      <span class="item-postage">
        <%= "配送料負担" %>
      </span>
    </div>
    <% if user_signed_in?%>
    <%if  current_user == @item.user%>
    <%= link_to "商品の編集", edit_item_path(@item.id), method: :get, class: "item-red-btn" %>
    <p class="or-text">or</p>
    <%= link_to "削除", item_path(@item.id), method: :delete, class:"item-destroy" %>
      <%end%>
      <%unless @item.user_id == current_user.id%>
    <%unless @item.order != nil %>
    <%= link_to "購入画面に進む",  item_orders_path(@item.id) ,class:"item-red-btn"%>
    <%end %>
    <%end%>
    <%end%>


    
    <%# //ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>

    <div class="item-explain-box">
      <span><%= "商品説明" %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @item.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%=Category.find(@item.item_category_id).name%></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= Statue.find(@item.item_statue_id).name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= Yamato.find(@item.yamato_id).name%></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= Area.find(@item.area_id).name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= Days.find(@item.days_id).name%></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>
  <div class="comment">
  <%@comments.each do |comment|%>
  <div class="comment-text">
  <%=comment.content%>
  </div>
  <div class="comment-user">
  <%=comment.user.nickname%>
  </div>
  <%end%>
  </div>
  <div id="comments">
  </div>
  <div class="comment-box">
    <%=form_with model:[@item,@comment],id:"comment-form", local: true do |f|%>
    <%=f.text_field :content,id:"text-field"%>
    <%=f.submit "送信",id:"comment-submit"%>
  </div>
  <%end%>
  <div class="links">
    <%unless @item.id - 1 == 0%>
    <%=link_to "＜前の商品＞", item_path(@item.id - 1),class:"change-item-btn"%>
    <%end%>
    <%unless @item.id ==  Item.count%>
    <%=link_to "＜後の商品＞", item_path(@item.id + 1),class:"change-item-btn"%>
    <%end%>
  </div>
  <%# 詳細ページで表示されている商品のカテゴリー名を表示しましょう %>
  <a href="#" class="another-item"><%= "商品のカテゴリー名" %>をもっと見る</a>
  <%# //詳細ページで表示されている商品のカテゴリー名を表示しましょう %>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Furima</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("furima-logo-color.png", class:"furima-icon"), "/" %>
    <%=search_form_for @p,url: items_search_path do |s|%>
    <%=s.label :item_name_eq%>
    <%=s.text_area :item_name_eq%>
    <%=s.collection_select :item_category_id_eq,@category,:id,:name,include_blank:"指定なし"%>
      <button class="search-button">
        <%s.submit %><%=image_tag "search.png", class:"search-icon" %>
      </button>
      <%= %>
      <%end%>
    
  </div>
  <div class='nav'>
  <ul>
    <li>カテゴリー</li>
    <li>カテゴリー</li>
    </ul>
    
      <div class="category">
                <% Category.all.each do |c|%>
                 <ul class="clist">
                 <li><%= c.name%></li>
                 </ul>

      </div>
      <%end%>
    
    <ul class='lists-right'>
      <%if user_signed_in?%>
      <li><%= link_to current_user.nickname, new_user_session_path, class: "user-nickname"%> </li> 
      <li><%= link_to 'ログアウト',  destroy_user_session_path, method: :delete, class: "logout" %></li>
      <%else%>
      <li><%= link_to 'ログイン', user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <%end%>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>FURIMA利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "furima-logo-color.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("furima-logo-color.png", class:"second-logo"), "/" %>
</header>